Dockerfile
components/atoms/DateModified.js
next.config.js
pages/index.js

There are no tasks for this but I figured it is sort of related to our versioning.
The code is mostly copied from Life-Journeys.
To test it, it needs to be pushed to main. This means that the date will only show on the deployed version (Dev or Prod).

Using TC build date as last date modifed.

---

Dockerfile

I think the build time for the last date modified did not work because I forgot to define it in our Dockerfile as an ARG.

Adding build_date arg.

---

components/atoms/ActionButton.test.js

Quick remove of the `custom` keyword for testing the ActionButton.

Removing the custom test.

---

pages/home.js

Fixed bug where API data was renamed to data causing Most Requested Pages to not show

apiData renamed to data

---

components/atoms/Meta.js
components/organisms/Layout.js

Moved meta data to push of analytics for more control
Analytics beacon should fire every time layout is rendered
Adobe Analytics group will have to test post PR merge
Zain will be moving Layout to _app.js ensuring it gets rendered on each page

Cleaned up Adobe Analytics code

---

components/molecules/SearchCard.test.js

As it turns out, [react-testing-library's helpers are all wrapped in act()](https://reactjs.org/docs/testing-recipes.html#act) so the error given by the console when we run tests doesn't make much sense. Mocking Next's Link component fixed the issue

stopped act wrap error from occurring

---

components/organisms/ImageBox.js
pages/home.js

Added a bool property for priority to the next/image so that it preloads the image if that image is above the fold. 
more info here. 
https://nextjs.org/docs/api-reference/next/image#priority

added image priority to imagebox component

---

next.config.js

As per our security training, security headers should be added to each page (probably somewhere global).
Below are the security headers to be added
// Only ever use HTTPS
{
key: "Strict-Transport-Security",
value: "max-age=31536000; includeSubDomains; preload",
},
// Prevents the browser from attempting to guess the type of content
{
key: "X-Content-Type-Options",
value: "nosniff",
},
// Only allow secure origin to be delivered over HTTPS
{
key: "Referrer-Policy",
value: "same-origin",
},
{
key: "Content-Security-Policy",
value: `frame-ancestors 'self'`,
},
**What to test for/How to test** 
Check the response headers in the network tab
NA

added security headers to pages

---

components/organisms/Layout.js
pages/index.js

I propose we apply layout to all pages. This allows us to tackle things globally in our app even with exceptions to the layout.
By default header/footer exist but can be toggled off for pages that do not require them.
- Apply layout to Index.js
- Header/Footer in layout can be toggled
It may be unnecessary to apply changes to Layout since we have the option to use _document.js as well

Apply layout to all pages

---

__tests__/pages/404.test.js
__tests__/pages/500.test.js
pages/404.js
pages/500.js

- Very short PR to add the 500.js and 404.js page. Both are empty.
- Added rendering tests in our unit tests.
- I couldn't figure out how to render the 500.js in dev mode. i think its built on purpose this way to help developers see the error message when running the app locally.

Dcwc 114 error pages

---

lib/pageContent.js

Shortened bilingual mappings by using `object[keyName + locale].value` instead of the old 3-line ternary expressions.
- Shortened bilingual mappings

shortened all bilingual mappings

---

tailwind.config.js

- Increase drop shadow opacity from 10% to 25% 
- Darker grey bar behind icons.

Increase drop shadow and grey in cards

---

components/molecules/BenefitApplicationCard.js

The text in the "You might be eligible" card didn't wrap and was extending over the icons and causing mobile to have a horizontal scroll bar. 
The link text now wraps and stays in the designated area. 
the LInk text is on the line below the other text.
made the paragraph text a p tag from an a tag as it didn't appear to be a link.
added an h2 for the card

fix for the overflowing text

---

components/molecules/DSHeader.js
components/organisms/Layout.js
locales/en.js
locales/fr.js
pages/dashboard.js
pages/profile.js

- Combined two smaller tickets
- Adds isAuth:true to profile page to display header menu
- Moves breadCrumbItems into page props in order to display custom breadcrumbs on each page
- Adds profile and security settings breadcrumb

DCWC-1780-1781 Profile Auth - Breadcrumbs on Account Page

---

pages/api/programData/cpp.js
pages/api/programData/ei.js

[DCWC-1885](https://jira-dev.bdm-dev.dts-stn.com/browse/DCWC-1885)
- Add a dummy access token to the interop api requests
This will be replaced with the token from RAOIDC once that authentication is in place.

adding a dummy access token for auth to API stubs

---

components/molecules/BenefitCardHeaderSummary.js
components/molecules/BenefitCardHeaderSummary.test.js
lib/Utils.js
locales/en.js
locales/fr.js

Adds localisation for dates and currencies on the cards. Also added a `formatMoney()` method for future convenience
- Localisation of dates and currencies
- Removed currency strings from locale files as they're no longer needed

Cards will now have localized date and currency strings

---

pages/api/programData/cpp.js
pages/api/programData/cppd.js
pages/api/programData/ei.js
pages/api/programData/gis.js
pages/api/programData/oas.js
pages/api/programData/seb.js
pages/dashboard.js

- Moves the mapping to the client side
Will fail tests
- uncomments the "current" benefit cards to test
- leaves the "processData" call in the API even though currently it's not doing anything (still a good function to keep)

Map client side

---

components/atoms/InfoSection.js
components/atoms/InfoSection.test.js
package-lock.json
package.json
pages/security-settings.js

- Adds a new component `InfoSection` based of of the `ProfileInfoSection`
- Adds a skeleton Security page to test it on
look a the ../security-settings page
The page will get updated later, and might not even call this component directly, just in place to test it.

adding InfoSection for Profile and Security pages

---

pages/dashboard.js

An warning occurred due to filtering no benefit cards without using useEffect
Open the console for /dashboard?userid=default
The console should no longer warn about div mismatches between server and client

Bug fix: client match server

---

pages/profile.js

Ensured that the common/similar elements between the profile page and security settings page are consistent and that the issue of being unable to focus on the "Manage your security settings" link is resolved.
Tab through the profile page and verify that the "Manage your security settings" link can be tabbed to.

Fixed tabbing to the security link

---

.teamcity/settings.kts

https://sc-digital-centre-release.bdm-dev.dts-stn.com/
Will now be 
https://sc-digital-centre-staging.bdm-dev.dts-stn.com/
A manual deploy will need to be run after merging to ensure the env is available

66244 Renamed release environment to staging

---

.github/workflows/sast.yml

Update SAST test trigger to only execute on PR open against main or dev branch
- Should trigger in this PR, but not after merge to dev.
- should also trigger again when PR is open from dev -> main
- [n/a] Tests added for key features and bugs
- [n/a] Deployment working

updating sast trigger

---

.teamcity/settings.kts

Adding a step to dynamic build to truncate the build name so that deployments don't fail for a bad formatted name based on the branch.

Adding a step to truncate build names

---

lib/api/mapBenefits.js
lib/api/mapBenefits.test.js
lib/api/mapBenefitsHelper.js
lib/api/mapBenefitsHelper.test.js

An example of mocking in tests that we should be working towards for cleaner unit testing
Ensure code and tests still work
Had to comment out a significant number of mapBenefits tests. They are better suited for cypress e2e testing

67653 Test flow prep work mocking
