.teamcity/README
.teamcity/pom.xml
.teamcity/settings.kts

adding files.

---

helm/charts/single-tier-application/values.yaml
package-lock.json
package.json

Updated next-template project name to sc-digital-centre

updated project name in package

---

.github/README.md

Starting our ReadMe file. I also added some basic steps to our TeamCity configurations.

Read me changes

---

.teamcity/settings.kts

When changing the settings of the VCS root from TeamCity, our settings.kts file gets overwritten with a new empty one.
this PR adds the settings back in the file? hopefully?

Adding kts settings to main.

---

CHANGELOG.md
Dockerfile

Adding changelog

---

.env.example
next.config.js
package-lock.json
pages/api/getData.js
pages/index.js

"Sample" code to get data from the AEM API (if available) or from a local file 
- Sample code on index,js that gets the data from for the page
- API code file.  
- N/A for now

DC-36 get data from aem

---

tailwind.config.js

Added the colours listed [here](https://www.figma.com/file/9LVfXvyx75Hh7H6eXrDBL4/Service-Canada-Digital-Centre-Design-System?node-id=5056%3A1429)

added colours from sc labs dc design system

---

helm/charts/sc-digital-centre/templates/deployment.yaml
helm/charts/sc-digital-centre/values.yaml
helmfile/helmfile.yaml
helmfile/overrides/sc-digital-centre/sc-digital-centre.yaml.gotmpl

- Added service annotations with correct URL and port for Prometheus to automatically scrape the app
- Removed the "root" ingress path in the dev environments (this is reserved for prod only)
helmfile --environment dev apply
verify in bdm-dev grafana that you can see the instance in the "NodeJS Test Dashboard" instance drop down

Prometheus troubleshooting

---

.github/workflows/test-and-lint.yml

added dev as well as main to the test and lint yaml file so that the tests will be run on either dev or main.
-
-

DC-5 added dev to branches on pull_request

---

components/atoms/Breadcrumb.js
components/atoms/Breadcrumb.test.js
package-lock.json
package.json
tailwind.config.js

Added breadcrumb component. It is not added to any page as it will be added from the home page and not the index (splash) page.
Also added basic tests.
`npm i` needs to be ran.
Then run `npm run test:unit`

Added Breadcrumb and tests.

---

components/atoms/DateModified.test.js

Added simple DateModified component tests.
Run `npm run test:unit` to see the tests run.

Added date Modified tests.

---

components/atoms/Breadcrumb.test.js
components/molecules/Footer.test.js

Added simple Footer tests.
Run `npm run test:unit`

Added Footer tests

---

components/molecules/Footer.test.js

Removing Footer test warnings as the props were required.

Removing test warnings.

---

components/atoms/ActionButton.js
components/atoms/ActionButton.test.js

Simpler ActionButton code
- Removed all the colours but the default 
- Removed unnecessary list of explicit named attributes

Simpler ActionButton

---

.husky/pre-commit
package-lock.json
package.json
pages/home.js

Fixed issue where non staged files were being committed by husky when linting
Update 2 files with bad linting.
Stage 1 of the files.
Commit files without pushing
Unstaged file should not be committed

Husky commit on lint fixed

---

pages/api/getData.js

Clean LGTM report

---

components/molecules/ServiceCanada.js
components/molecules/ServiceCanada.test.js
pages/home.js

Figma (Desktop):
Figma (Mobile):
Currently, or desktop version of the component will take the full width. This will be fixed when creating the containers for the home page. (Its built with flex and girds so the component is flexible and responsive)

Dcwc 462 service account

---

package-lock.json

added up-to-date package-lock file

---

components/atoms/SearchBar.js
components/molecules/SearchCard.js
components/molecules/SearchHeader.js
components/molecules/SearchHeader.test.js
locales/en.js
locales/fr.js
pages/searchResult.js

Added a search bar header section to the search results page.
- Added search header and related component
- Added tests for search header

copied everything from dcwc-639

---

components/organisms/Layout.js
pages/_document.js

Temporarily removing adobe analytics due to builds failing

Temporarily removed adobe analytics for test

---

.teamcity/settings.kts

Adobe removed setting to see if it is root cause

---

.teamcity/settings.kts

Testing solution for broken build with vcs pointing to main

Adding vcs root to main

---

.teamcity/settings.kts

changed Vcs name

---

.teamcity/settings.kts

Added branch spec

---

.teamcity/settings.kts

Revert kts changes for Ben to debug in a fresh state

reverting vcs root tests

---

.teamcity/settings.kts
Dockerfile

Reverted Alpine image and added vault secrets.

Trying to fix deployement.

---

components/atoms/Meta.js
components/organisms/Layout.js
package-lock.json
pages/_document.js

Added adobe analytics back as was not the root cause of the issue

Added adobe analytics back

---

.teamcity/settings.kts

adjusting build configs

---

.teamcity/settings.kts

declaring vcs in project settings

---

.teamcity/settings.kts

updating script

---

.github/workflows/e2e-test.yml
.github/workflows/test-and-lint.yml
__tests__/pages/home.test.js
components/molecules/FeatureBlock.test.js
components/organisms/Layout.js
package-lock.json
pages/api/getData.js
pages/home.js

With help from TOM and Marco, the featured benefit title, description and image are now getting pulled from AEM
Note that there are 3 warnings for act(...) that still need to be resolved.

DCWC-678 - Get benefit text from AEM

---

pages/searchResult.js

Removed unnecessary code.

---

__tests__/pages/home.test.js
__tests__/pages/searchResult.test.js
components/molecules/CardList.js
components/molecules/CardList.test.js
pages/api/getData.js
pages/home.js
pages/searchResult.js

Wired up AEM content to benefit cards
- Benefit cards content comes from AEM
- Tests adjusted to reflect AEM structure for now
Run application and view benefit cards to see if data resembles AEM content provided
There is room for improvement. We should structure the data better, leverage state and come up with a common way to handle translations

Wire benefit card data

---

.teamcity/settings.kts
helmfile/helmfile.yaml

Added release environment.

---

.teamcity/settings.kts

Missing head

---

.teamcity/settings.kts
helmfile/helmfile.yaml

Release builds

---

.teamcity/settings.kts

removed admin from k8s and added tag as filter.

---

.teamcity/settings.kts

Renaming VCSRoot

---

.teamcity/settings.kts

refreshing

---

.teamcity/settings.kts

Removed release build

---

.teamcity/settings.kts

added tag build.

---

components/atoms/Card.js
components/molecules/CardList.js
components/molecules/SearchCard.js
components/organisms/ImageBox.js
pages/home.js

(jira doesn't seem to be working)
Added an image to the search bar area
Updated the Cards so that they grow in the row to the size of the card with the largest amount of text. 
Had to futz with the button to make it as it was before. 
Tried not to break anything.

added image for search adjust heights of cards

---

.github/README.md
__tests__/pages/home.test.js
__tests__/pages/searchResult.test.js
components/molecules/CardList.js
components/molecules/CardList.test.js
pages/api/getData.js
pages/home.js

AEM Model changed scShortDescriptionEn to scDescriptionEn
AEM Model changed scProgram to scProgramEn
Had to change date to dates for caching issues in our pipeline.
Will create Jira ticket to resolve

changed program and short description

---

package-lock.json
package.json

Updated package to include prop-types as it is missing and another potential cause for the 500 error on Dev

Missing package

---

next.config.js

Added CSP and STS headers to all pages for our application.
- Added CSP header
- Added SRS header
- other headers that may be required can be added to the header function in `next.config.js`

Content Security Policy (CSP) and Strict-Transport-Security (STS) Headers

---

locales/en.js
locales/fr.js

added link and title to english and french locale files
- modified locale files
- download and check
- Isn't this information supposed to be coming from AEM ???

DCWC-717 Updated text and link for callback

---

__tests__/api/aemService.test.js
jest.config.js
jest.setup.js
pages/api/aemService.js
pages/home.js

- added changed files from feat/aem-service branch and signed this time!

AEM Service

---

pages/benefits/[id].js
pages/searchResult.js

- Test site banner has text in it now
- Age options on the search filters are now a bit more reasonable

Banner names and more age options

---

__tests__/pages/home.test.js
__tests__/pages/searchResult.test.js
components/molecules/CardList.js
components/molecules/CardList.test.js
pages/api/aemService.js
pages/api/getData.js
pages/benefits/[id].js
pages/home.js
pages/searchResult.js

- Updated aem service to get the benefits, changed name to getBenefit instead 
- Updated getBenefit to read new data structure
- Updated home page to use new functions 
- Updated searchResults page to use AEM Service 
- Updated CardList to use new data structure
- Updated tests to use new data structure
- Faked dynamic benefit pages to pass build because Zain will be doing changes
- download and try 
- dynamically created pages were not updated or tested as this will be modified by Zain
-

Updates to read from Alpha 

---

.teamcity/settings.kts
helmfile/helmfile.yaml
helmfile/overrides/sc-digital-centre/sc-digital-centre.yaml.gotmpl

Updating our TC Scripts to include just two jobs, one for release (manual deploys  to a release environment) and one for all other branches that get pushed, creating a url for each.  Helm scripts are adjusted to handle these deployments and create those environments dynamically.

Pond dynamic branches

---

__tests__/pages/home.test.js
locales/en.js
locales/fr.js
pages/home.js

Fetching top tasks from AEM
- Added a call for the dictionary in AEM. That is where all titles and other miscellaneous things will reside. There are different ways to implement it so please be constructively judgmental.

Getting top tasks from AEM

---

.github/workflows/comment-environment.yml

Dynamically adding environment to PR by comments

example comment

---

.teamcity/settings.kts

attempting to enforce lowercase

---

components/atoms/PhaseBanner.js
cypress/integration/home.spec.js
cypress/integration/splash.spec.js
pages/index.js

Added some e2e tests for the splash page.
added a11y tests for the splash and home page
Added a role for the banner
the splash page was missing a title
-
The click to show the home page is flaky and needs some work. It seems to take some time to display the page.

DCWC945-updated e2e tests and a11y

---

cypress/integration/home.spec.js
cypress/integration/splash.spec.js
pages/index.js

The purpose was to fix the alignment of the text in the buttons. 
used the action button (as it wasn't created when this page was done) 
Used next/image for the graphic as there is a warning about it in the console,  although it was more of an exercise and example as there isn't much of a benefit from using it in this particular case. 
Updated a some of the tests to add in the home page. 
Make sure that the graphic and the buttons look ok. The active state now looks like Alpha site. 
There is some discussion about whether the action button can be split into a link button and an action button and we can still do that.

Dcwc 988 splash

---

components/atoms/SearchBar.js
components/molecules/SearchCard.js
cypress/integration/home.spec.js
pages/home.js
pages/search.js

Added encoding to the query string with cypress tests.

Encoding query string

---

components/organisms/Layout.js
pages/_document.js
pages/index.js

AA was breaking when going straight to the home page due to scrips loading out of order.
-Moved satellite script to _document,js to force it to the bottom of every page
Navigate around page. Go to other pages and return
This can only be tested when in a PR so may need additional work

Fixed adobe analytics bug

---

next.config.js

[DCWC-1010](https://jira-dev.bdm-dev.dts-stn.com/browse/DCWC-1010) (Jira Issue)
Description
Added security headers: X-Frame-Options: SAMEORIGIN
What to test for/How to test: check in the network tab for "X-Frame-Options: SAMEORIGIN" in the response headers
Additional Notes: NA

Added x-frame-options header

---

.github/README.md
.github/workflows/e2e-test.yml
.github/workflows/test-and-lint.yml

Added badges for e2e and unit tests passing or failing. 
Added the links for the badges for main and dev
I am not sure the main ones will work. ??

Dc 1008 badges

---

components/atoms/ActionButton.js
components/atoms/Card.js
components/atoms/ContactCard.js
components/atoms/Meta.js
components/molecules/CardList.js
components/molecules/ContactUs.js
components/molecules/Header.js
components/molecules/Menu.js
components/molecules/ServiceCanada.js
components/organisms/Layout.js
pages/benefits/[id].js
pages/home.js
pages/index.js
pages/search.js

Standardising props
- Cleaning up specified props to only be defined in proptypes
Ensure app still runs smoothly

Dcwc 1109 standardise props

---

__tests__/pages/splash.test.js
components/atoms/Meta.js
components/atoms/Meta.test.js
components/organisms/Layout.js
lib/pageContent.js
next.config.js
pages/_document.js
pages/api/AEMServiceClass.js
pages/benefits/[id].js
pages/home.js
pages/index.js
pages/search.js

DCWC-797 (discover how/where to put metadata for the home page)
Description
Merged Zains changes manually into the pr from https://github.com/DTS-STN/sc-digital-centre/pull/135/files to fit in with AEMrevamp pr
Metadata added to application
Metadata included in layout and applied globally
What to test for/How to test
Ensure metadata exist on all pages
Additional Notes
Had to manually change a few pieces from Zain's PR but overall it should be similar
AEMrevamp needs to be merged first before reviewing and merging is pr as those changes are included

Dcwc 797 metadata

---

__tests__/pages/splash.test.js
components/atoms/Card.js
components/molecules/CardList.js
components/molecules/FeatureBlock.js
components/molecules/Footer.js
components/molecules/SearchCard.js
components/molecules/SearchHeader.test.js
components/molecules/ServiceCanada.js
cypress/integration/splash.spec.js
pages/benefits/[id].js
pages/home.js
pages/index.js
pages/search.js

Added and removed proptypes as needed.

Cleaning up Proptypes throughout the app.

---

components/molecules/SplashLanguageSelect.js
components/molecules/SplashLanguageSelect.test.js
components/organisms/MostRequestedPages.js
components/organisms/MostRequestedPages.test.js
pages/home.js
pages/index.js

- Extracted components such that the page code would be more readable

Dcwc 1105 clean up pages

---

__tests__/pages/home.test.js
__tests__/pages/search.test.js
components/atoms/Meta.test.js
components/molecules/CardList.test.js
components/molecules/Header.js
components/molecules/SearchCard.js
components/organisms/MostRequestedPages.test.js
lib/pageContent.js
next.config.js
pages/benefits/[id].js

very small list of changes but it also contains part 1/2 
- fix the language toggle removing unnecessary id query 
- fix the benefits href address 
- see deployment branch

Dcwc xxx i18n fixv3 - Part 2/2

---

.github/workflows/test-and-lint.yml

Commented out a line in the yml for action and changed another line to hopefully work for both main and dev if there is no comment already.

updated yml file for tests

---

components/atoms/SearchBar.js
styles/fonts.css

Incredible fix to our awesome production environment.

Tailwind fix

---

.teamcity/settings.kts

add pipeline for dashboard

---

.github/README.md

testing pipeline

---

pages/dashboard.js

- Added a blank dashboard pages
- The addition of the page added the route/dashboard
- Header and Footer not yet added to the page as were waiting on the design system header/footer components to be ready and added

Blank dashboard route

---

components/atoms/BenefitCardHeader.jsx
components/atoms/VerticalStepper.jsx
components/molecules/BenefitCard.jsx
components/molecules/OasBenefitCard.jsx
locales/en.js
pages/_app.js
pages/dashboard.js
styles/stepper.css

- Adding BenefitCard component
- Adding BenefitCardHeader component
- Adding OAS Details component
- Adding Vertical Stepper component

Benefit Card Component & OAS

---

components/molecules/BenefitCard.jsx
components/molecules/PendingBenefitCard.jsx
locales/en.js
pages/dashboard.js

- Creating "PendingBenefitCard" component to use for all pending benefits
- Add CPP Pending card

Develop CPP Pending Card

---

components/atoms/BenefitCardHeaderPending.jsx
components/molecules/BenefitCard.jsx
components/molecules/PendingBenefitCard.jsx
styles/stepper.css

- Made the pending benefit card responsive
-
- The active card is not responsive yet (card itself is WIP still)
- Refactoring for the BenefitCard component needs to be done to isolate CSS styles more
- Tablet sized views need need be addressed

Responsive pending benefit cards

---

components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderActive.test.js
components/molecules/ActiveBenefitDetails.js
components/molecules/ActiveBenefitDetails.test.js

- Adding unit test for ActiveBenefitDetails component
- Adding unit test BenefitCardHeaderActive component

Adding unit test for Active Benefit Cards (Header and Details)

---

__tests__/components/atoms/BenefitCardHeaderPending.test.js
__tests__/components/atoms/HorizontalRule.test.js
__tests__/components/atoms/__snapshots__/BenefitCardHeaderPending.test.js.snap
__tests__/components/atoms/__snapshots__/HorizontalRule.test.js.snap
__tests__/components/molecules/PendingBenefitDetails.test.js
__tests__/components/molecules/__snapshots__/PendingBenefitDetails.test.js.snap
package-lock.json

- Snapshot test cases for `<HorizontalRule />`, `<BenefitCardHeaderPending/>`,  `<PendingBenefitDetails />`

Some missing snapshot tests for components

---

__tests__/pages/__snapshots__/dashboard.test.js.snap

fix dashboard snapshot

---

package-lock.json

Fixing moderate vulnerability with follow-redirects

audit fix for moderate vulnerability

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
pages/dashboard.js

- Add gis card to dashboard
-
-

dcwc 1329 gis card

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/molecules/BenefitApplicationCard.js
pages/dashboard.js

- Condensed card for CPPD
- Updated dashboard snapshot tests

Condensed CPPD card

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
contents/DashboardBenefitTasksConstants.js

- Adding link for EI reporting to pending and active EI cards
- Updating test snapshots

Add link for EI reporting

---

package-lock.json
package.json

- Installing design system package
-

Install Design System

---

package-lock.json
package.json

Merge dev inti dashboard 2mar

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderActive.test.js
components/molecules/BenefitCard.js
contents/DashboardBenefitCardConstants.js
contents/DashboardBenefitTasksConstants.js
locales/en.js
pages/dashboard.js

- Creating CPPD Active card
- Using benefitType instead of benefitName to display card's title
- Update unit test snapshots

Creating the CPPD Active Card

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/molecules/ActiveBenefitDetails.js
contents/DashboardBenefitTasksConstants.js
locales/en.js
locales/fr.js
package-lock.json

- Links from MSCA were added to the tasks for EI benefit cards
- Tests were already written in the past as part of different PR

Links from MSCA added to EI tasks

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderInactive.js
components/atoms/BenefitCardHeaderInactive.test.js
components/molecules/BenefitCard.js
constants/BenefitStatus.js
contents/DashboardBenefitCardConstants.js
contents/DashboardBenefitTasksConstants.js
locales/en.js
locales/fr.js
pages/dashboard.js
tailwind.config.js

- Developing BenefitCardHeaderInactive component
- Adding inactive EI and CPPD cards
- Adding BenefitStatus constant
- Adding Unit test for BenefitCardHeaderInactive

Inactive Benefits cards (EI & CPPD)

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderPending.js
components/molecules/PendingBenefitDetails.test.js
locales/en.js
locales/fr.js

add latest update label to active and pending cards header
fixed a failing test
-
-

add latest update to cards

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderActive.test.js
components/molecules/BenefitCard.test.js
package-lock.json
package.json

- Added the dollar sign for payment amounts for English & French

DCWC-1475 Dollar sign

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/NoBenefitCardHeader.test.js
components/molecules/NoBenefitCard.js
components/molecules/NoBenefitCard.test.js
contents/DashboardBenefitTasksConstants.js
contents/DashboardNoBenefitCardConstants.js
pages/dashboard.js

- Develop the No Benefits card EI
- Adding Unit test for NoBenefitCard and NoBenefitCardHeader

Feature/dcwc1461 No-Benefit card EI

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
__tests__/pages/dashboard.test.js
contents/DashboardBenefitTasksConstants.js
contents/DashboardNoBenefitCardConstants.js
locales/en.js
locales/fr.js
pages/dashboard.js

- add no benefit card for OAS and GIS
-

no benefit oas gis

---

.teamcity/settings.kts

Added secret fix

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/molecules/BenefitTasks.js

Left align the icons

---

__tests__/pages/404.test.js
pages/404.js

- Adding Design System Error page
-

Adding Design System Error page

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderInactive.js
components/atoms/BenefitCardHeaderInactive.test.js
components/molecules/BenefitCard.js
components/molecules/NoBenefitCard.js

- Removing View More button from The CPPD inactive card
- Removing View More button from The EI inactive card
- Removing View More button from NoBenefitCard with less than 7 tasks
- Match title of  CPPD inactive card with Figma

EI and CPPD - Remove view more

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/molecules/DSHeader.js
components/molecules/Greeting.js
components/molecules/__snapshots__/DSHeader.test.js.snap
locales/en.js
locales/fr.js
pages/dashboard.js

Adding Greeting component

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderActive.js

- Fixed bold lettering issue on Next Payment Date Text

DCWC-1557 Bold lettering

---

Dockerfile
package-lock.json
package.json

Instead of merging a bunch of Snyk vulnerabilities they are merged together to update dev.
This is to stop merge issues and conflicts with package/package-lock

Updating vulnerabilities

---

components/atoms/BenefitDetailPart.js
components/atoms/BenefitDetailPart.test.js
components/molecules/ActiveBenefitDetails.js

- Updating some of my edits from previous change to remove duplicate code.
-

moving duplicate code to component

---

__tests__/pages/__snapshots__/dashboard.test.js.snap
components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderPending.js
contents/DashboardBenefitCardConstants.js
locales/en.js
locales/fr.js

- Update latest status part in upper right of card header

Update status in upper right of card

---

components/molecules/DSHeader.js
locales/en.js
locales/fr.js
package-lock.json
package.json

- Updating Design System package
- Changing DS Header props

Updating Design System package

---

.github/workflows/comment-environment.yml
.teamcity/settings.kts

Updated the integration branch link action from /home to /dashboard
-
-

updated the branch link

---

__tests__/pages/profile.test.js
locales/en.js
locales/fr.js
pages/profile.js

Adding the Profile page with Header and Footer.
Run branch locally, click Manage Profile under My Service Canada Account.

Adding Profile page skeleton.

---

Dockerfile
package-lock.json
package.json

updating next to 12.1.5 and specifying node image versions in docker file.  Also adding non-root user control to docker file for security purposes.

Fixing the broken app :)

---

components/atoms/ProfileInfoSection.js
components/atoms/ProfileInfoSection.test.js
components/molecules/ProfileInfo.js
components/molecules/ProfileInfo.test.js
pages/profile.js

- Task to be created.
- Layout will come with a later PR
- Figma design: https://www.figma.com/file/wLUT8UWdL6MjSD8j8vHw0t/Dashboard---Design-File?node-id=7373%3A149000

Adding Profile Information Section.

---

package-lock.json
package.json

- Updated Design System Package for incoming changes to the header

DCWC-1647 Update Design System Header

---

components/molecules/DSHeader.js
locales/fr.js
pages/400.js
pages/404.js
pages/500.js
pages/503.js
pages/dashboard.js
pages/index.js
pages/profile.js

- Fixed header language toggle
- Generating linkPath in getStaticProps to pass to header

DCWC-1273 Get the French toggle working

---

objects/BenefitSummaries.js
objects/UniversalBenefit.js
pages/dashboard.js

- adding logic to map api data to object
-

Map api generic object

---

objects/UniversalBenefit.js
pages/dashboard.js

- adding the links to map API result to advertising cards display logic
-

using the codes to match data

---

components/atoms/SettingsNavButton.js
components/atoms/tabList.js
components/atoms/tabList.test.js
locales/en.js
locales/fr.js
pages/profile.js

Creating the main tab list on the profile page.
- `npm run dev`
- Navigate to [localhost:3000/](http://localhost:3000/profile) 
- Click both tabs and see the page content change.

Profile page tabbing

---

package-lock.json
package.json

Updated Next version to fix deployments

Updated next to 12.1.6

---

components/molecules/UniversalBenefitCard.js
objects/UniversalBenefit.js
pages/500.js

Mapping the used (Active EI & CPP) task lists to generic benefit objects on creation based on program and status.
The `objects/UniversalBenefit.js` file is clearly in need of some clean up (proper file organisation) - that is coming.

1704 map task lists

---

components/atoms/ProfileInfoSection.js
components/atoms/ProfileInfoSection.test.js
components/molecules/ProfileInfo.js
components/molecules/ProfileInfo.test.js
locales/en.js
locales/fr.js
pages/profile.js

Following the [mockup](https://www.figma.com/file/wLUT8UWdL6MjSD8j8vHw0t/Dashboard---Design-File?node-id=7373%3A148999)

Adding Security content on profile page.

---

pages/profile.js

Small bug fix

---

pages/dashboard.js

Changed server side props to static until runtime env available

serverside to static

---

components/atoms/StatusBadge.js
components/molecules/BenefitCardHeaderSummary.js
components/molecules/BenefitCardHeaderSummary.test.js
components/molecules/UniversalBenefitCard.js
lib/BenefitsMapping.js

fixing the propTypes definitions and some other tweaks

fixing some errors caused by wrong propTypes

---

pages/_app.js
pages/dashboard.js

- API path needed configuring to work on /fr/ pages
- New layout container takes breadcrumb props

Fixed API loading programs in French

---

components/molecules/UniversalBenefitCard.js

Extremely small PR to add background color from Breanna's request.

Adding gray bg for tasks

---

components/atoms/ViewMoreLessButton.js

Copy paste error and there was a missing slash that made the icon not appear in french. 
fixed the path. 
-
-

fixed the path for the icon

---

components/molecules/BenefitCard.js
components/molecules/BenefitTasks.js

Small change for styling. (I forgot to extend the background color all the way across.)

small background color change

---

components/atoms/ActionButton.js
components/atoms/BenefitCardHeaderActive.js
components/atoms/BenefitCardHeaderActiveAgreement.js
components/atoms/BenefitCardHeaderInactive.js
components/atoms/BenefitCardHeaderPending.js
components/atoms/NoBenefitCardHeader.js
components/atoms/ViewMoreLessButton.js
components/molecules/BenefitApplicationCard.js
components/molecules/BenefitCard.js
components/molecules/BenefitTasks.js
components/molecules/UniversalBenefitCard.js

Match task list to figma
long words in french were extending past divider in the card header
Smaller text for some of the sizes so that long words can fit. 
- the tasks are displayed as in the Figma.
-

updates to the task list and font sizes

---

components/molecules/BenefitCardHeaderSummary.js
components/molecules/BenefitCardHeaderSummary.test.js
constants/SummaryTypes.js
contents/DashboardBenefitTasksConstants.js
lib/BenefitsMapping.js
locales/en.js
locales/fr.js

- Updated french content for existing mocked cards
- Will need further french content updates as more cards are mocked

DCWC-1784 Updated existing french content

---

.teamcity/settings.kts

Auth enabled for release

---

components/atoms/StatusBadge.js
components/molecules/BenefitCard.js
components/molecules/BenefitCardHeaderSummary.js
components/molecules/BenefitTasks.js
components/molecules/UniversalBenefitCard.js
components/molecules/UniversalBenefitCard.test.js
locales/en.js
locales/fr.js

- Updating the headings so they have a screen reader flow intend by client
- Updated a few elements to lists so screen reader will more easily iterate though them
- Added some translated screen reader only text
Edits to the BenefitCard component were not supper well thought out out as it's expected to be removed, so were just to make the tests pass.

updating the heading hierarchy

---

__tests__/pages/dashboard.test.js
components/molecules/BenefitCardHeaderSummary.test.js
components/molecules/UniversalBenefitCard.test.js
constants/CPPDMappingCodes.js
constants/ProgramCodes.js
contents/BenefitCards.js
contents/DashboardBenefitTasksConstants.js
lib/BenefitsMapping.js
locales/en.js
locales/fr.js
mockdata/user1/cppd.json
mockdata/user2/cppd.json
pages/api/programData/cpp.js
pages/api/programData/cppd.js
pages/api/programData/ei.js

@TishamIslam co created
Added mocked active CPPD
- CPPD active benefit mocked
- Added CPPD codes
Renamed BenefitMapping functions

DCWC-1770 Mocked active cppd

---

constants/EIMappingCodes.js
contents/DashboardBenefitTasksConstants.js
lib/BenefitsMapping.js
mockdata/MockData.js
mockdata/userDefault/ei.json
pages/api/programData/ei.js
pages/dashboard.js

WIP
- Tweaked MapEICards to mock cards of all states
- Added In Payment Mock to default EI mocks

DCWC-1794 Mock EI Cards

---

constants/EIMappingCodes.js
constants/ProgramTypeCodes.js
constants/StatusCodes.js
contents/DashboardBenefitTasksConstants.js
lib/BenefitsMapping.js
locales/en.js
locales/fr.js
mockdata/userDefault/ei.json

- Added default ei mocks that mock all states of the card

DCWC-1794 Added ei defaults

---

components/molecules/DSFooter.js
components/organisms/Layout.js

- pass the local to dsFooter for translation
- fix missing required props

Fix footer translation

---

components/molecules/BenefitCardHeaderSummary.js
lib/BenefitsMapping.js
locales/en.js
locales/fr.js
mockdata/user1/ei.json

added EI sickness card for mock scenario user 1
re-ordered some of the items to match the Figma for the card.

Dcwc 1837 user1

---

components/molecules/NoBenefitCard.js
components/molecules/UniversalBenefitCard.js
contents/DashboardBenefitTasksConstants.js

- Fixed summaries as a required prop when not all cards take summaries
- Fixed issue with CPPD task list not expanding

Fixed errors and cppd task list bug

---

components/atoms/ProfileInfoSection.js
pages/profile.js

The tabs do not look like the Figma design since we are waiting on the tab component from DECD Design System.
The content reflects Figma.

Profile page sub tabs functionality

---

package-lock.json
package.json

- Updated design system to v. 1.38.0

DCWC-1858 Design System Update v. 1.38.0

---

components/atoms/ViewMoreLessButton.js
components/molecules/BenefitTasks.test.js
contents/DashboardBenefitTasksConstants.js
locales/en.js
locales/fr.js

- Aligned tasks and task headers with master components
- Added some missing translations (WIP)

Task and Translation Alignment

---

lib/api/mapBenefits.test.js
mockdata/userDefault/ei.json

- Adds test for EI Mapping data
- Tests are based on status as key functional differences lie there
- Tests based on math logic being done
Identify any gaps in testing

Test ei mapping

---

__tests__/pages/400.test.js
__tests__/pages/404.test.js
__tests__/pages/500.test.js
__tests__/pages/503.test.js
__tests__/pages/dashboard.test.js
components/molecules/DSHeader.test.js
components/molecules/NoBenefitCard.test.js

Removing all unit test warnings.

Removed all warnings from unit tests.

---

components/atoms/StatusBadge.js
components/atoms/StatusBadge.test.js
components/molecules/UniversalBenefitCard.js

Remove translations from status badge
Pushed logic to UniversalBenefitCard temporarily

Remove translations from status badge

---

lib/api/mapBenefits.test.js
mockdata/userDefault/cpp.json
mockdata/userDefault/cppd.json

- Adds tests for CPP & CPPD, mapping program, status, type, number of summaries, and number of task groups.
- Adds tests for CPP & CPPD date calculations
- Revises the order in the CPP & CPPD default mock jsons to flow somewhat more logical.
Data in the JSONs wasn't changed, just re-ordered.

adding tests for CPP and CPPD

---

constants/CPPMappingCodes.js
constants/EIMappingCodes.js
constants/GISMappingCodes.js
constants/OASMappingCodes.js
contents/DashboardBenefitTasksConstants.js
lib/api/mapBenefits.js

- updating look-ups for prop reference
- removing unused task lists (bonus)
Validate that all the cards still render without error
This kind of lookup can be more error prone, but more common in a key/value pair model which is way faster (even if in this instance the speed is negligible). The look-ups are being done within a try catch of the API fetch so will be handled there if Interop passes us unexpected data. This is in line with a "fail fast" programming style (we want' the code to break if something unexpected happens, so we take notice sooner and can fix it faster)

Update to Key/Value pair look-up

---

lib/mapSummaries.js

- make a check for undefined summaries before executing a function on them
- https://sc-digital-centre-dev.bdm-dev.dts-stn.com/dashboard?userid=default (loads until it crasshes)

check for undefined summaries

---

lib/Utils.js
lib/mapSummaries.js
lib/mapSummaries.test.js
lib/utils.test.js

- Adding test for the lib files
- Fixed some bugs with the date (forcing a time code injection to ensure the right date is returned)
- Fixed a bug in money, remove the currency code in french

Add lib tests

---

tailwind.config.js

It was desired to have the colours come from the DS has so some had to be adjusted slightly. 
The lighter palette was chosen as per figma

updated the colours as per DS

---

.teamcity/settings.kts

Toggling auth on for dynamic branches
- Auth enabled to test ECAS implementation
- App should still work as usual

Auth for dynamic branches

---

.teamcity/settings.kts

Add ECAS well known env to deployment

Add ECAS well known env to deployment

---

__tests__/pages/dashboard.test.js
components/molecules/UniversalBenefitCard.js

- Cleans up the dashboard tests
- Separates tests properly
- Fixes undetermined test for specific test id
- Cleans up issues in console messages when running the tests

Fix dashboard tests

---

components/molecules/BenefitApplicationCard.js
components/molecules/BenefitApplicationCard.test.js
locales/en.js
locales/fr.js

Updated the styling on the advertising cards to match Figma
-
-

style update for ad cards

---

components/molecules/BenefitTasks.js
components/molecules/BenefitTasks.test.js
components/molecules/Greeting.test.js
components/molecules/NoBenefitCard.test.js
pages/profile.js

- Cleaning up some tests, and errors found in code

cleaning up test warnings

---

.github/workflows/pr-comments.yml

- use the package the code was built for (not sure how it worked the first time...)

Update package for comment action 

---

contents/BenefitTasksGroups.js

- Quick change to the CPPD Task list
- Note to relay this change to content team

DCWC-1995 - Remove tasks from CPPD Disability

---

components/atoms/StatusBadge.js
components/atoms/ViewMoreLessButton.js
components/molecules/BenefitApplicationCard.js

Updated the layout and text colour for the ad cards with more information. 
updated the icon for more or less button and estimate link. 
made sure the font weight for the status badge was set to 500 
-

Dcwc style update

---

__tests__/pages/dashboard.test.js
pages/dashboard.js

- Update the name of the set cookie function (latest package update change the name)
The use of our cookies still works as expected

update set cookie method for new one

---

.github/README.md
components/molecules/DSFooter.js
components/molecules/DSHeader.js
components/molecules/Greeting.js
components/organisms/Layout.js
package-lock.json
package.json
pages/400.js
pages/404.js
pages/500.js
pages/503.js
pages/profile.js
pages/security-settings.js

- Update decd-design-system to service-canada-design-system (same package, new name)
Nothing unexpected in the design.

updating design system package name

---

constants/CPPMappingCodes.js
constants/ProgramTypeCodes.js
constants/StatusCodes.js
constants/SummaryTypes.js
contents/BenefitTasks.js
contents/BenefitTasksGroups.js
lib/api/mapBenefits.js
lib/api/mapBenefits.test.js
lib/mapCallout.js
lib/mapCallout.test.js
lib/mapSummaries.js
lib/mapSummaries.test.js
locales/en.js
locales/fr.js
mockdata/userDefault/cpp.json
pages/dashboard.js

- Added new status Paid for death benefit card
- Added Death Benefit Card (Paid, Application Received)
- Existing issue with Task Groups that might require a second look (A specific TypeCode CPPDeath needs its own set of tasks outside of CPP?)

DCWC-1613 Build Death Benefit Card

---

contents/BenefitTasks.js
locales/en.js

Added "Change" to my tax deductions text
-
-

updated text for tax deductions

---

lib/api/mapBenefits.js
pages/dashboard.js

- This should fix that infinite loop on dashboard we were seeing yesterday

adding error handling

---

components/molecules/LoadingState.js
components/molecules/LoadingState.test.js
pages/dashboard.js

- Added loading state content until all benefits are loaded or errors occur.

Loading state added.

---

.github/dependabot.yml
.github/workflows/pull-request.yml

- Add dependabot monitoring of github-actions and docker
- Limit how many PRs dependabot can open at a time (5 across all packages. _excludes vulnerabilities_)
- Specify the interval to weekly for when dependable can open new PRs
To monitor over time.
- [_n/a_] Tests added for key features and bugs

update create comment action

---

__mocks__/aemMock.js
__tests__/pages/dashboard.test.js
graphql/queries/dashboardQuery.graphql
lib/aem/mapper.js
pages/dashboard.js

This PR is a first step to get connected to AEM. For now, the query only fetches
` scPageNameEn
scPageNameFr
scTitleEn
scTitleFr`
.

63866 AEM integration

---

.github/README.md

- Update links in readme to point to the correct badges
- Added links for code coverage in main
See the readme https://github.com/DTS-STN/sc-digital-centre/tree/readme-reports#readme
- [n/a] Tests added for key features and bugs

Readme reports

---

components/molecules/UniversalBenefitCard.js

- Added transition for expansion/collapse of universal benefit card
-

Expand/Collapse Card Interaction

---

next.config.js

- Fixed config to apply CSP to all paths 
- This should clear some of the ZAP issues
- Security policy is now a response header on the splash page

Fix Zap Errors - CSP Not Set

---

next.config.js
pages/dashboard.js

- Added security attributes to cookie on dashboard page
-  disabled X-Powered-By in Next Config

Fix Zap Errors - Cookie Config-PoweredBy

---

.github/README.md

Adding some links to the new documentations, 
Cleaning up some older stuff.
- [n/a] Tests added for key features and bugs
- [n/a] Deployment working

Update Readme doc links

---

.teamcity/settings.kts

set the script to bash

---

.teamcity/settings.kts

Script bash

---

.teamcity/settings.kts

A quick edit to change Build_Staging target to our branch "main".

Changing target to main.

---

__tests__/pages/dashboard.test.js
components/molecules/Greeting.test.js
components/molecules/NoBenefitCard.test.js
locales/en.js
next.config.js

Running scripts doesn't generate any warnings - can look at the automated scripts run on PR, or run them yourself with 
- `npm run test`
- `npm run lint`
- `npm run build`
- `npm run start`

Ado 67136 Cleanup console warnings for tests and build

---

.teamcity/settings.kts

Cleaned up auth environment variables as PR is stabilising
Trying multi line command args for readability

Renamed auth environment variables

---

.teamcity/settings.kts

Multiline requires 3 quotes instead of a single quote

Kotlin config error
